[project]
name = "technicalchallenge"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.7",
    "pillow>=12.0.0",
    "requests>=2.32.5",
]
